---
#
# Installing Java 8
#


- name: Update APT package manager repositories cache
  become: true
  apt:
   update_cache: yes

# Install Java 

- name: Install Java 8
  apt:
   name: openjdk-8-jdk
   state: present
   update_cache: yes
